In [3]:
import torch
import numpy as np
print(torch.__version__)

2.2.1


In [4]:
tensor1 = torch.tensor([0,1,2,3,4,5])
print("My 1st tensor",tensor1)

narray = np.arange(10)
tensor2 = torch.from_numpy(narray)
print("My 2nd tensor", tensor2)

My 1st tensor tensor([0, 1, 2, 3, 4, 5])
My 2nd tensor tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [5]:
print("Zeroth element:", tensor1[0])
print("Last element:", tensor1[-1])

Zeroth element: tensor(0)
Last element: tensor(5)


In [6]:
print("The shape of tensor2 is", tensor2.size())
print("The dim of tensor2 is", tensor2.dim())

The shape of tensor2 is torch.Size([10])
The dim of tensor2 is 1


In [7]:
a = torch.tensor([[2,5,7], [11,15,18]])
print(a)
print("The shape of a is:", a.shape)
print("The dim of a is:", a.dim())
print(a[1, 1])

a[1,1] = 99
print(a)

tensor([[ 2,  5,  7],
        [11, 15, 18]])
The shape of a is: torch.Size([2, 3])
The dim of a is: 2
tensor(15)
tensor([[ 2,  5,  7],
        [11, 99, 18]])


In [10]:
a = torch.rand(5,2, dtype=torch.float64)
print(a)
print()

b = torch.zeros_like(a)
print(b)

tensor([[0.9234, 0.3473],
        [0.4856, 0.3794],
        [0.8445, 0.2767],
        [0.0501, 0.9579],
        [0.5679, 0.6208]], dtype=torch.float64)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)


In [12]:
t1 = torch.arange(9, dtype=torch.float32)
print(t1)

print("\nViewing as a row")
row_t1 = t1.view(1,9)
print(row_t1)
print(row_t1.shape)

print("\nViewing as a col")
col_t1 = t1.view(9,1)
print(col_t1)
print(col_t1.shape)

print("\nViewing as matrix")
mat_t1 = t1.view(3,3)
print(mat_t1)
print(mat_t1.shape)

print(t1)

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8.])

Viewing as a row
tensor([[0., 1., 2., 3., 4., 5., 6., 7., 8.]])
torch.Size([1, 9])

Viewing as a col
tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.]])
torch.Size([9, 1])

Viewing as matrix
tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])
torch.Size([3, 3])
tensor([0., 1., 2., 3., 4., 5., 6., 7., 8.])


In [13]:
dt = torch.arange(15)
print("Before modification")
print(dt)

print("\nIntermediate Step")
ndt = dt.view(5,3)
print(ndt)
ndt[:, 2] = 0
print(ndt)

print("\nAfter modification")
print(dt)

Before modification
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Intermediate Step
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])
tensor([[ 0,  1,  0],
        [ 3,  4,  0],
        [ 6,  7,  0],
        [ 9, 10,  0],
        [12, 13,  0]])

After modification
tensor([ 0,  1,  0,  3,  4,  0,  6,  7,  0,  9, 10,  0, 12, 13,  0])


In [17]:
a = torch.rand(4,4, dtype=torch.float32)
b = torch.arange(1,17,dtype=torch.float32).view(4,4)

print("Tensor a")
print(a)

print("\nTensor b")
print(b)

print("\nAddition")
print(a + b)

print("\nSubtraction")
print(a - b)

print("\nMultiplication")
print(a * b)

print("\nDivision")
print(a / b)

print("\nMatrix Multiplication")
print(torch.mm(a,b))

Tensor a
tensor([[0.9574, 0.6812, 0.6144, 0.0699],
        [0.3182, 0.1887, 0.5122, 0.2284],
        [0.0922, 0.7973, 0.4554, 0.7960],
        [0.3310, 0.4899, 0.5086, 0.5170]])

Tensor b
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]])

Addition
tensor([[ 1.9574,  2.6812,  3.6144,  4.0699],
        [ 5.3182,  6.1887,  7.5122,  8.2284],
        [ 9.0922, 10.7973, 11.4554, 12.7960],
        [13.3310, 14.4899, 15.5086, 16.5170]])

Subtraction
tensor([[ -0.0426,  -1.3188,  -2.3856,  -3.9301],
        [ -4.6818,  -5.8113,  -6.4878,  -7.7716],
        [ -8.9078,  -9.2027, -10.5446, -11.2040],
        [-12.6690, -13.5101, -14.4914, -15.4830]])

Multiplication
tensor([[0.9574, 1.3625, 1.8431, 0.2797],
        [1.5912, 1.1324, 3.5851, 1.8274],
        [0.8297, 7.9727, 5.0092, 9.5514],
        [4.3032, 6.8591, 7.6285, 8.2712]])

Division
tensor([[0.9574, 0.3406, 0.2048, 0.0175],
        [0.0636, 0.0315, 0.0732, 0.0286],
   

In [22]:
a = torch.rand(5,8)

# Scalar
print((a + 5).shape)
print()

# Basic broadcasting
b = torch.rand(1,8)
print(b.shape)
print((a + b).shape)
print()

# Broadcasting
b = torch.rand(5,1)
print(b.shape)
print((a+b).shape)

torch.Size([5, 8])

torch.Size([1, 8])
torch.Size([5, 8])

torch.Size([5, 1])
torch.Size([5, 8])


In [25]:
import torch
import time

# Assuming `torch_metal` is a hypothetical library/module that enables PyTorch to use Apple Metal
from torch_metal import to_metal

a = torch.rand(512, 1024)
b = torch.rand(1024, 2048)

t1 = time.time()
torch.mm(a, b)
t2 = time.time()

# Convert tensors to use Metal instead of CUDA
ag = to_metal(a)
bg = to_metal(b)

t3 = time.time()
torch.mm(ag, bg)
# Assuming synchronization method for Metal (similar to CUDA's synchronize)
torch_metal.synchronize()
t4 = time.time()

print("Time taken in CPU matmul is", t2 - t1, "seconds")
print("Time taken by GPU matmul is", t4 - t3, "seconds")
print(f"That is a {((t2-t1)/(t4-t3)):.1f}X speedup!")


ModuleNotFoundError: No module named 'torch_metal'