# EECS 545 (WN 2024) Homework 3 Q2: Implementing Soft Margin SVM by Optimizing Primal Objective

<span class="instruction">Before starting the assignment, please fill in the following cell.</span>

In [1]:
###################################################################
# Enter your first and last name, e.g. "John Doe"                 #
# for example                                                     #
__NAME__ = "Shashank Verma"                                       #
__UNIQID__ = "shaaero"                                         #
###################################################################
# raise NotImplementedError("TODO: Add your implementation here.")
###################################################################
#                        END OF YOUR CODE                         #
###################################################################

print(f"Your name and email: {__NAME__} <{__UNIQID__}@umich.edu>")
assert __NAME__ and __UNIQID__

Your name and email: Shashank Verma <shaaero@umich.edu>


# Support Vector Machine (SVM)
In this notebook you will implement the SVM algorithm, using batch gradient descent and stochastic gradient descent.

After implementing the SVM, you will report the trained parameters (**w**, b) for batch gradient descent.

## Setup code
Before getting started, we need to run some boilerplate code to set up our environment. You'll need to rerun this setup code each time you start the notebook. Let's start by checking whether we are using Python 3.11 or higher.

In [2]:
import sys
if sys.version_info[0] < 3:
    raise Exception("You must use Python 3")

if sys.version_info[1] < 11:
    print("Autograder will execute your code based on Python 3.11 environment. Please use Python 3.11 or higher to prevent any issues")
    print("You can create a conda environment with Python 3.11 like 'conda create --name eecs545 python=3.11'")
    raise Exception("Python 3 version is too low: {}".format(sys.version))
else:
    print("You are good to go")

You are good to go


First, run this cell load the [autoreload](https://ipython.readthedocs.io/en/stable/config/extensions/autoreload.html) extension. This allows us to edit `.py` source files, and re-import them into the notebook for a seamless editing and debugging experience.

In [3]:
%load_ext autoreload
%autoreload 2

Once you located the `soft_margin_svm.py` correctly, run the following cell allow us to import from `soft_margin_svm.py`. If it works correctly, it should print the message:
```Hello from soft_margin_svm.py```

In [4]:
from soft_margin_svm import hello
hello()

/Users/shashank/Dropbox (University of Michigan)/UMich/Courses/Winter 2024/EECS 545/Homework 3/HW3_rev0/soft_margin_svm.py:11: SyntaxWarning: invalid escape sequence '\p'
  """
/Users/shashank/Dropbox (University of Michigan)/UMich/Courses/Winter 2024/EECS 545/Homework 3/HW3_rev0/soft_margin_svm.py:47: SyntaxWarning: invalid escape sequence '\p'
  """


Hello from soft_margin_svm.py


Then, we run some setup code for this notebook: Increase the default figure size.

In [5]:
from IPython.display import display_html, HTML

display_html(HTML('''
<style type="text/css">
  .instruction { background-color: yellow; font-weight:bold; padding: 3px; }
</style>
'''));

## Load the dataset
The following codebase will load the dataset. It prints out the key and dimension of matched value matrix.

In [6]:
import numpy as np
import os
filename = 'data/soft_margin_svm/soft_margin_svm_data.npy'

if not os.path.exists(filename):
    print(f'Oops! We failed to find the data file {filename}')
else:
    data = np.load(filename, allow_pickle=True).item()
    
    for k, v in data.items():
        print(f'Key "{k}" has shape {v.shape}')
        print(f'First three rows of {k} are {v[:3]}')

Key "x_train" has shape (76, 4)
First three rows of x_train are [[5.7 4.4 1.5 0.4]
 [4.9 3.1 1.5 0.1]
 [6.  2.2 4.  1. ]]
Key "y_train" has shape (76, 1)
First three rows of y_train are [[ 1.]
 [-1.]
 [ 1.]]
Key "x_test" has shape (24, 4)
First three rows of x_test are [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]]
Key "y_test" has shape (24, 1)
First three rows of y_test are [[ 1.]
 [-1.]
 [-1.]]


Note: make sure our y has -1 or 1.

In [7]:
print(np.unique(data['y_train']))

[-1.  1.]


## Implement batch gradient descent

<span class="instruction">We will implement the batch gradient descent-based training in `svm_train_bgd` function in `soft_margin_svm.py` </span> and then test with `svm_test`. 

In [32]:
from soft_margin_svm import svm_train_bgd, svm_test

W, b = svm_train_bgd(data['x_train'], data['y_train'])

if np.all(W == 0):
    print('you should update W')
if np.all(b == 0):
    print('you should update b')
    
accuracy = svm_test(W, b, data['x_test'], data['y_test'])
print(f'The accuracy of batch gradient descent-based SVM is {accuracy*100:4.2f}%')

The accuracy of batch gradient descent-based SVM is 95.83%


/Users/shashank/Dropbox (University of Michigan)/UMich/Courses/Winter 2024/EECS 545/Homework 3/HW3_rev0/soft_margin_svm.py:11: SyntaxWarning: invalid escape sequence '\p'
  """
/Users/shashank/Dropbox (University of Michigan)/UMich/Courses/Winter 2024/EECS 545/Homework 3/HW3_rev0/soft_margin_svm.py:58: SyntaxWarning: invalid escape sequence '\p'
  - W: Numpy array of shape (1, num_features).


Following the task in the question, we will run `svm_train_bgd` over 5 times, with changing the iteration. The next cell shows the outcome. If the accuracy decrease over time, you may want to revisit your implementation. You are required to <span class="instruction"> report those test accuracies as well as the trained weights (b and **W**) in your **writeup** </span>.

In [33]:
from soft_margin_svm import svm_train_bgd, svm_test


for num_epochs in [1, 3, 10, 30, 100]:
    W, b = svm_train_bgd(data['x_train'], data['y_train'], num_epochs)
    accuracy = svm_test(W, b, data['x_test'], data['y_test'])
    print(f'[NumEpochs: {num_epochs}] Accuracy: {accuracy * 100:4.2f}%')
    print(f'b: {b}, W: {W}')

[NumEpochs: 1] Accuracy: 54.17%
b: [0.01], W: [[ 0.224  -0.0855  0.545   0.206 ]]
[NumEpochs: 3] Accuracy: 54.17%
b: [0.02], W: [[ 0.44848122 -0.17019759  1.08918105  0.41163421]]
[NumEpochs: 10] Accuracy: 95.83%
b: [-0.14], W: [[-0.1648026  -0.80606447  1.37816462  0.57445096]]
[NumEpochs: 30] Accuracy: 95.83%
b: [-0.175], W: [[-0.20885861 -0.69979483  1.30489009  0.56605151]]
[NumEpochs: 100] Accuracy: 95.83%
b: [-0.315], W: [[-0.28240917 -0.77529188  1.75856715  0.82441652]]
